database: "archive/cardio_train.parquet"
result_location: "results/"
outlier_detection_technique: "combo"
machine_learning_model: 'lstm'
automate_feature_selection: false
use_one_predictor: false
use_global_accuracy: true
use_one_model_type: false
expand_data_multiplier: 0
expanded_file_name: null
full_accuracy: false
planned_clusters: 2
approximate_sampled_rows: 10000000
sampling_seed: 17
sample_max_attempts: 5
num_processes: 22
index_column_name: 'Index'

runtime_parameters:
#    choice_0:
#      predictor: microcontroller_id
#      clustering: unsupervised
#      cluster_alg: Minhal
#      accuracy: 1
#      split_size: 4
#      preprocess_data: false
#      postprocess_data: true
#      batch_size: "2MB"
#      batch_method: exhaustive_search
#    choice_1:
#      predictor: microcontroller_id
#      clustering: unsupervised
#      cluster_alg: Minhal
#      accuracy: 1
#      split_size: 4
#      preprocess_data: false
#      postprocess_data: true
#      batch_size: "4MB"
#      batch_method: exhaustive_search
#    choice_2:
#      predictor: microcontroller_id
#      clustering: unsupervised
#      cluster_alg: Minhal
#      accuracy: 1
#      split_size: 4
#      preprocess_data: false
#      postprocess_data: true
#      batch_size: "8MB"
#      batch_method: exhaustive_search
#    choice_3:
#      predictor: microcontroller_id
#      clustering: unsupervised
#      cluster_alg: Minhal
#      accuracy: 1
#      split_size: 4
#      preprocess_data: false
#      postprocess_data: true
#      batch_size: "16MB"
#      batch_method: exhaustive_search
#    choice_4:
#      predictor: microcontroller_id
#      clustering: unsupervised
#      cluster_alg: Minhal
#      accuracy: 0.25
#      split_size: 4
#      preprocess_data: false
#      postprocess_data: true
#      batch_size: "256MB"
#      batch_method: exhaustive_search
#    choice_5:
#      predictor: microcontroller_id
#      clustering: unsupervised
#      cluster_alg: Minhal
#      accuracy: 0.5
#      split_size: 4
#      preprocess_data: false
#      postprocess_data: true
#      batch_size: "256MB"
#      batch_method: exhaustive_search
    choice_6:
      predictor: weight
      clustering: supervised
      cluster_alg: KM
      accuracy: 1
      split_size: 50
      preprocess_data: false
      postprocess_data: true
      batch_size: "256MB"
      batch_method: exhaustive_search
#    choice_7:
#      predictor: microcontroller_id
#      clustering: unsupervised
#      cluster_alg: Minhal
#      accuracy: 2.5
#      split_size: 4
#      preprocess_data: false
#      postprocess_data: true
#      batch_size: "256MB"
#      batch_method: exhaustive_search
#    choice_8:
#      predictor: microcontroller_id
#      clustering: unsupervised
#      cluster_alg: Minhal
#      accuracy: 5
#      split_size: 4
#      preprocess_data: false
#      postprocess_data: true
#      batch_size: "256MB"
#      batch_method: exhaustive_search
#    choice_10:
#      predictor: microcontroller_id
#      clustering: unsupervised
#      cluster_alg: Minhal
#      accuracy: 1
#      split_size: 4
#      preprocess_data: false
#      postprocess_data: true
#      batch_size: "1GB"
#      batch_method: exhaustive_search


# Specifies the behavior for missing values
handle_nulls:
  age:
    method: outliers
    replacement_value: -1
  gender:
    method: outliers
    replacement_value: -1
  height:
    method: outliers
    replacement_value: -1
  weight:
    method: outliers
    replacement_value: -1
  ap_hi:
    method: outliers
    replacement_value: -1
  ap_lo:
    method: outliers
    replacement_value: -1
  cholesterol:
    method: outliers
    replacement_value: -1
  gluc:
    method: outliers
    replacement_value: -1
  smoke:
    method: outliers
    replacement_value: -100
  alco:
    method: outliers
    replacement_value: -300
  active:
    method: outliers
    replacement_value: -1
  cardio:
    method: outliers
    replacement_value: -1


# Specifies which features are used to predictors for other features
# Example is based off the slide 9 of ADBIS Presentation slides
# If automate_feature_selection is set to true, this section will be ignored
predicted_by:
  age:
    predictors:
      - "weight"
    accuracy: 1
    model: 'lstm'
    clustering: unsupervised
    cluster_alg: Minhal
    batch_method: exhaustive_search
  gender:
    predictors:
      - "weight"
    accuracy: 1
    model: 'lstm'
    clustering: unsupervised
    cluster_alg: Minhal
    batch_method: exhaustive_search
  height:
    predictors:
      - "weight"
    accuracy: 1
    model: 'lstm'
    clustering: unsupervised
    cluster_alg: Minhal
    batch_method: exhaustive_search
  ap_hi:
    predictors:
      - "weight"
    accuracy: 1
    model: 'lstm'
    clustering: unsupervised
    cluster_alg: Minhal
    batch_method: exhaustive_search
  ap_lo:
    predictors:
      - "weight"
    accuracy: 1
    model: 'lstm'
    clustering: unsupervised
    cluster_alg: Minhal
    batch_method: exhaustive_search
  cholesterol:
    predictors:
      - "weight"
    accuracy: 1
    model: 'lstm'
    clustering: unsupervised
    cluster_alg: Minhal
    batch_method: exhaustive_search
  gluc:
    predictors:
      - "weight"
    accuracy: 1
    model: 'lstm'
    clustering: unsupervised
    cluster_alg: Minhal
    batch_method: exhaustive_search
  smoke:
    predictors:
      - "weight"
    accuracy: 1
    model: 'lstm'
    clustering: unsupervised
    cluster_alg: Minhal
    batch_method: exhaustive_search
  alco:
    predictors:
      - "weight"
    accuracy: 1
    model: 'lstm'
    clustering: unsupervised
    cluster_alg: Minhal
    batch_method: exhaustive_search
  active:
    predictors:
      - "weight"
    accuracy: 1
    model: 'lstm'
    clustering: unsupervised
    cluster_alg: Minhal
    batch_method: exhaustive_search
  cardio:
    predictors:
      - "weight"
    accuracy: 1
    model: 'lstm'
    clustering: unsupervised
    cluster_alg: Minhal
    batch_method: exhaustive_search
